#version 460
#extension GL_GOOGLE_include_directive : require

#include "view_transform.glsl"

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 7, std430) writeonly buffer LayoutProbe
{
    vec4 values[];
} layoutProbe;

void main()
{
    layoutProbe.values[gl_GlobalInvocationID.x] =
        viewConstants.record.clipAndJitter +
        viewConstants.record.viewport;
}
